### ISSUE TITLE
Panic on launch.

### ISSUE THREAD

**Issue by marcusramberg** [lahsivjar/grafonnet-playground#7] opened 2020-06-22 13:54 UTC
When trying to run as documented in the readme, I see the following:

```
 docker run \                                                                                                                    15:51:25
    -e "GRAFANA_URL=http://localhost:3000/" \
    -e "GRAFANA_API_KEY=redacted==  \
    -e "GRAFONNET_PLAYGROUND_FOLDER_ID=HqNRC0ZMz" \
    -e "GIN_MODE=release" \
    -p 8080:8080 \
    lahsivjar/grafonnet-playground:1.2.0
panic: key GRAFANA_POST_URL is not set

goroutine 1 [running]:
github.com/lahsivjar/grafonnet-playground/config.mustHaveString(0xc2d865, 0x10, 0xc0001ca2c0, 0xb09d60)
	/src/config/config.go:71 +0x12d
github.com/lahsivjar/grafonnet-playground/config.Load(0xc0000a6ea0)
	/src/config/config.go:55 +0x234
main.main()
	/src/main.go:17 +0x70```

**Comment by marcusramberg** [comment] 2020-06-22 14:20
I kept going and set it up with post_url and get_url, but when I eventually got the linking with grafana right, it dies with this error instead:
```
2020/06/22 14:18:40 [Recovery] 2020/06/22 - 14:18:40 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:82 (0x4422f0)
/usr/local/go/src/runtime/signal_unix.go:390 (0x44211f)
/src/grafana/priority_queue.go:59 (0xa43975)
/src/grafana/grafana.go:78 (0xa42dcf)
/src/handlers/run.go:47 (0xa943cd)
/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 (0x9859c9)
/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/recovery.go:83 (0x998969)
/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 (0x9859c9)
/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/logger.go:240 (0x997a10)
/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 (0x9859c9)
/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:389 (0x98eeb1)
/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:351 (0x98e6e3)
/usr/local/go/src/net/http/server.go:2774 (0x6be5d7)
/usr/local/go/src/net/http/server.go:1878 (0x6ba1c0)
/usr/local/go/src/runtime/asm_amd64.s:1337 (0x459b90)
```

**Comment by kubicgruenfeld** [comment] 2020-06-22 15:08
Same here. It happsens since the release of 1.0.0. Versions before did work well.

**Comment by lahsivjar** [comment] 2020-06-23 03:47
Hi @kubicgruenfeld @marcusramberg ,

Can you share your configuration files?

**Comment by lahsivjar** [comment] 2020-06-23 04:07
I have invited the root cause, it happens when the cleaner is not enabled. You can do one of the following to fix the issue:

1. Update to use version 1.2.1 ( I have pushed the fix there)
2. Enable cleaner job with `AUTO_CLEANUP` set to true

Let me know if you still face any problems

**Comment by lahsivjar** [comment] 2020-06-24 02:58
@kubicgruenfeld @marcusramberg Did the above work for you?

**Comment by marcusramberg** [comment] 2020-06-24 05:17
Confirmed. No longer crashed. Thanks :)

**Closed** 2020-06-24 06:54 UTC
